// <auto-generated />
using System;
using InformeObras.Infraestructura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InformeObras.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(ContextoBaseDatos))]
    [Migration("20260504143010_ModeloRelacionalInformes")]
    partial class ModeloRelacionalInformes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InformeObras.Infraestructura.Persistencia.Entidades.Foto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_key");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<long>("SistemaId")
                        .HasColumnType("bigint")
                        .HasColumnName("sistema_id");

                    b.Property<string>("UrlPublica")
                        .HasColumnType("text")
                        .HasColumnName("url_publica");

                    b.HasKey("Id");

                    b.HasIndex("SistemaId");

                    b.ToTable("fotos");
                });

            modelBuilder.Entity("InformeObras.Infraestructura.Persistencia.Entidades.Informe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Conclusiones")
                        .HasColumnType("text")
                        .HasColumnName("conclusiones");

                    b.Property<string>("Cuatrimestre")
                        .HasColumnType("text")
                        .HasColumnName("cuatrimestre");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Modificado")
                        .HasColumnType("text")
                        .HasColumnName("modificado");

                    b.Property<string>("NombreObra")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_obra");

                    b.Property<bool>("Protegido")
                        .HasColumnType("boolean")
                        .HasColumnName("protegido");

                    b.Property<string>("Tecnico")
                        .HasColumnType("text")
                        .HasColumnName("tecnico");

                    b.HasKey("Id");

                    b.ToTable("informes");
                });

            modelBuilder.Entity("InformeObras.Infraestructura.Persistencia.Entidades.Sistema", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("InformeId")
                        .HasColumnType("bigint")
                        .HasColumnName("informe_id");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<int>("Prefijo")
                        .HasColumnType("integer")
                        .HasColumnName("prefijo");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("InformeId");

                    b.ToTable("sistemas");
                });

            modelBuilder.Entity("InformeObras.Infraestructura.Persistencia.Entidades.Tarea", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool>("NoOk")
                        .HasColumnType("boolean")
                        .HasColumnName("no_ok");

                    b.Property<string>("NotaTarea")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nota_tarea");

                    b.Property<bool>("Ok")
                        .HasColumnType("boolean")
                        .HasColumnName("ok");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<bool>("Rev")
                        .HasColumnType("boolean")
                        .HasColumnName("rev");

                    b.Property<long>("SistemaId")
                        .HasColumnType("bigint")
                        .HasColumnName("sistema_id");

                    b.HasKey("Id");

                    b.HasIndex("SistemaId");

                    b.ToTable("tareas");
                });

            modelBuilder.Entity("InformeObras.Infraestructura.Persistencia.Entidades.Foto", b =>
                {
                    b.HasOne("InformeObras.Infraestructura.Persistencia.Entidades.Sistema", "Sistema")
                        .WithMany("Fotos")
                        .HasForeignKey("SistemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("InformeObras.Infraestructura.Persistencia.Entidades.Sistema", b =>
                {
                    b.HasOne("InformeObras.Infraestructura.Persistencia.Entidades.Informe", "Informe")
                        .WithMany("Sistemas")
                        .HasForeignKey("InformeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Informe");
                });

            modelBuilder.Entity("InformeObras.Infraestructura.Persistencia.Entidades.Tarea", b =>
                {
                    b.HasOne("InformeObras.Infraestructura.Persistencia.Entidades.Sistema", "Sistema")
                        .WithMany("Tareas")
                        .HasForeignKey("SistemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("InformeObras.Infraestructura.Persistencia.Entidades.Informe", b =>
                {
                    b.Navigation("Sistemas");
                });

            modelBuilder.Entity("InformeObras.Infraestructura.Persistencia.Entidades.Sistema", b =>
                {
                    b.Navigation("Fotos");

                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
