// <auto-generated />
using System;
using System.Text.Json;
using InformeObras.Infraestructura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InformeObras.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(ContextoBaseDatos))]
    [Migration("20260504075802_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InformeObras.Infraestructura.Persistencia.Entidades.Informe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Cuatrimestre")
                        .HasColumnType("text")
                        .HasColumnName("cuatrimestre");

                    b.Property<JsonDocument>("Datos")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("datos");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Modificado")
                        .HasColumnType("text")
                        .HasColumnName("modificado");

                    b.Property<string>("NombreObra")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_obra");

                    b.HasKey("Id");

                    b.ToTable("informes");
                });
#pragma warning restore 612, 618
        }
    }
}
