export const CUADRO_ELECTRICO_TEMPLATE = {
  secciones: [
    {
      titulo: "0. PREPARACIÓN DOCUMENTACIÓN",
      tipo: "simple",
      prefijo: 0,
      tareas: [
        { descripcion: "Crear espacio - CHAT", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Crear orden de fabricación para sinóptico", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Sinóptico", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Revisión sinóptico", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Subir sinóptico al chat", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Actualizar estado proyecto-Excel de seguimiento", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Entregar sinóptico a Pascual", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Anotar si reutilizamos materiales", rev: false, ok: false, noOk: false, notaTarea: '' },
      ]
    },
    {
      titulo: "1. DOCUMENTACIÓN",
      tipo: "simple",
      prefijo: 1,
      tareas: [
        { descripcion: "Crear carpeta (Cuadro eléctrico)", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Esquemas (Cuadro eléctrico) - Revisión esquemas", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Subir esquemas al chat", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Configuración cuadro (Cuadro eléctrico)", grupo: "1.3 Diseño cuadro", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Diseño puerta (Cuadro eléctrico)", grupo: "1.3 Diseño cuadro", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Revisión configuración", grupo: "1.3 Diseño cuadro", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Comprobar stock armarios", grupo: "1.4 Revisión de stock (PYME)", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Comprobar stock variadores", grupo: "1.4 Revisión de stock (PYME)", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Comprobar stock artículos (Actualizar Stock Pyme)", grupo: "1.4 Revisión de stock (PYME)", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Todo OK - Pedir soporte (Chat y Correo)", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Material cuadro (Previstos + Pedido)", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "IMPRIMIR: Esquemas, Sinóptico, Configuración cuadro, Lista materiales cuadro, Parte horas cuadro (poner horas)", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Etiqueta maniobra(2,9)", grupo: "1.6 Archivo etiquetas", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Etiqueta fuerza(3,5)", grupo: "1.6 Archivo etiquetas", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Amarillas (15x9)", grupo: "1.6 Archivo etiquetas", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Blancas (40x25)", grupo: "1.6 Archivo etiquetas", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Pulsantería (26,5x17,5)", grupo: "1.6 Archivo etiquetas", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Rombo (29x8)", grupo: "1.6 Archivo etiquetas", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Crear acceso directo (Obras en proceso)", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Poner obra en código de cuadros (Excel)", rev: false, ok: false, noOk: false, notaTarea: '' },
      ]
    },
    {
      titulo: "2. PREPARACIÓN MATERIALES",
      tipo: "simple",
      prefijo: 2,
      tareas: [
        { descripcion: "Comprobar 1. DOCUMENTACIÓN", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Comprobar si lleva soporte/orejas/anclado", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Llevar puerta a corte + USB (Archivo DXF)", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Hacer caja preparación materiales", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Imprimir etiquetas: Amarillas, Blancas, Pulsantería, Bornas, Rombo, Etiqueta maniobra, Etiqueta fuerza", rev: false, ok: false, noOk: false, notaTarea: '' },
      ]
    },
    {
      titulo: "3. CABLEADO CUADRO",
      tipo: "simple",
      prefijo: 3,
      tareas: [
        { descripcion: "Comprobar materiales", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "CORREGIR A MANO ESQUEMAS ELÉCTRICOS", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Corte máquina agua (Archivo DXF)", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Montaje canaleta + carril DIN", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Instalar componentes + pegatinas", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Cablear fuerza", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Dejar regulado los guardamotores a In", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Cablear maniobra/comunicación", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Puerta + otros elementos externos", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Realizar agujero para seccionador", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Tapa canaletas + Pega. blancas(40x25)", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Elementos conexionado externo: Barra de tierras, Grapas apantallado, Canal entrada cables", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Pegatinas GTM y Riesgo eléctrico", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Actualizar esquemas eléctricos (Autocad)", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Soporte/fijación cuadro", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Comprobar cuadro (sin tensión)", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Comprobar cuadro (con tensión)", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Limpieza cuadro", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "A dejar dentro cuadro: Esquemas, Manuales, Etiquetas, Sinóptico, Materiales", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Rellenar orden y parte horas (PYME)", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Fotos cuadro eléctrico (Subir a su carpeta)", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Guardar fotos cuadro + documentación", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Envolver/empaquetar cuadro (poner nombre obra)", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Escanear documentos (Subir a oficina)", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "IMPRIMIR CARTEL DE SACAR ALBARÁN", rev: false, ok: false, noOk: false, notaTarea: '' },
      ]
    },
    {
      titulo: "4. COSAS A TENER EN CUENTA (EN TALLER)",
      tipo: "simple",
      prefijo: 4,
      tareas: [
        { descripcion: "Ubicación cuadro eléctrico", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Acometida eléctrica", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Cable ethernet/comunicaciones", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Tubos enterrados", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Reutilización de canalización", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Reutilización materiales", rev: false, ok: false, noOk: false, notaTarea: '' },
      ]
    },
    {
      titulo: "5. PREPARACIÓN MATERIALES PARA LLEVAR A OBRA (EN TALLER)",
      tipo: "simple",
      prefijo: 5,
      tareas: [
        { descripcion: "Cuadro auxiliares/caja empalmes", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Mangueras", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Rejiband+ soportes", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Tubos+soportes", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Sensores", rev: false, ok: false, noOk: false, notaTarea: '' },
      ]
    },
    {
      titulo: "6. PROCESO INSTALACIÓN (EN OBRA)",
      tipo: "simple",
      prefijo: 6,
      tareas: [
        { descripcion: "Comprobar 5.0 Preparación mat...", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Trabajos a realizar por cuenta cliente: Cable ethernet, Acometidas", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Planificación canalización", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Instalar cuadro", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Instalar canalización", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Cajas empalmes", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Tirar cables", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Conexión cables - Conexión cuadro", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Conexión cables - Conexión equipos", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Reapriete cuadro eléctrico", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Verificar tensión cuadro eléctrico", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Desbloquear bombas (Ventilador)", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Comprobar conexionado - Sensores / Entradas PLC", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Comprobar conexionado - Electroválvulas", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Comprobar conexionado - Instalar sirena", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Comprobar conexionado - Motores/Bombas (intensidad en vacío)", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Rellenar 'Parte materiales obra'", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Fotos cajas empalme y cuadro", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Subir a carpeta obra las fotos", rev: false, ok: false, noOk: false, notaTarea: '' },
      ]
    },
    {
      titulo: "7. PARAMETRIZAR EQUIPOS (EN OBRA)",
      tipo: "simple",
      prefijo: 7,
      tareas: [
        { descripcion: "Comprobar 6 Proceso instalación", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Config. parámetros analógicos", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Config. parámetros variadores", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Config. Hora en plc y hmi", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Prueba en manual equipos (HMI)", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Prueba en auto por zonas", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Prueba AUTO 100%", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Comprobar alarmas", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Ajustar parámetros si precisa", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Copiar o foto de parámetros: HMI/PLC, Variadores, Esquemas eléctricos", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Explicación cliente", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Rellenar parte albarán y materiales", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Verificar que esté archivado: Programa, Parámetros, Fotos, Esquemas, Acceso directo borrado", rev: false, ok: false, noOk: false, notaTarea: '' },
      ]
    },
    {
      titulo: "8. IMPORTANTE PUESTA EN MARCHA BOMBAS",
      tipo: "simple",
      prefijo: 8,
      tareas: [
        { descripcion: "Todas las bombas con ventilador hay que moverlas del ventilador o eje para desbloquear el cierre mecánico", rev: false, ok: false, noOk: false, notaTarea: '' },
        { descripcion: "Las bombas sobre bancada antes de ponerlas en marcha hay que grabar un video donde se vea alineado el acoplamiento de los ejes", rev: false, ok: false, noOk: false, notaTarea: '' },
      ]
    }
  ]
};
